// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Beacon is an object representing the database table.
type Beacon struct {
	ID          int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Bssid       string    `boil:"bssid" json:"bssid" toml:"bssid" yaml:"bssid"`
	ClassRoomID int64     `boil:"class_room_id" json:"class_room_id" toml:"class_room_id" yaml:"class_room_id"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *beaconR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L beaconL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BeaconColumns = struct {
	ID          string
	Bssid       string
	ClassRoomID string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	Bssid:       "bssid",
	ClassRoomID: "class_room_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// BeaconRels is where relationship names are stored.
var BeaconRels = struct {
	ClassRoom string
}{
	ClassRoom: "ClassRoom",
}

// beaconR is where relationships are stored.
type beaconR struct {
	ClassRoom *ClassRoom
}

// NewStruct creates a new relationship struct
func (*beaconR) NewStruct() *beaconR {
	return &beaconR{}
}

// beaconL is where Load methods for each relationship are stored.
type beaconL struct{}

var (
	beaconColumns               = []string{"id", "bssid", "class_room_id", "created_at", "updated_at"}
	beaconColumnsWithoutDefault = []string{"bssid", "class_room_id", "created_at", "updated_at"}
	beaconColumnsWithDefault    = []string{"id"}
	beaconPrimaryKeyColumns     = []string{"id"}
)

type (
	// BeaconSlice is an alias for a slice of pointers to Beacon.
	// This should generally be used opposed to []Beacon.
	BeaconSlice []*Beacon
	// BeaconHook is the signature for custom Beacon hook methods
	BeaconHook func(context.Context, boil.ContextExecutor, *Beacon) error

	beaconQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	beaconType                 = reflect.TypeOf(&Beacon{})
	beaconMapping              = queries.MakeStructMapping(beaconType)
	beaconPrimaryKeyMapping, _ = queries.BindMapping(beaconType, beaconMapping, beaconPrimaryKeyColumns)
	beaconInsertCacheMut       sync.RWMutex
	beaconInsertCache          = make(map[string]insertCache)
	beaconUpdateCacheMut       sync.RWMutex
	beaconUpdateCache          = make(map[string]updateCache)
	beaconUpsertCacheMut       sync.RWMutex
	beaconUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
)

var beaconBeforeInsertHooks []BeaconHook
var beaconBeforeUpdateHooks []BeaconHook
var beaconBeforeDeleteHooks []BeaconHook
var beaconBeforeUpsertHooks []BeaconHook

var beaconAfterInsertHooks []BeaconHook
var beaconAfterSelectHooks []BeaconHook
var beaconAfterUpdateHooks []BeaconHook
var beaconAfterDeleteHooks []BeaconHook
var beaconAfterUpsertHooks []BeaconHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Beacon) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Beacon) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Beacon) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Beacon) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Beacon) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Beacon) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Beacon) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Beacon) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Beacon) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	for _, hook := range beaconAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBeaconHook registers your hook function for all future operations.
func AddBeaconHook(hookPoint boil.HookPoint, beaconHook BeaconHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		beaconBeforeInsertHooks = append(beaconBeforeInsertHooks, beaconHook)
	case boil.BeforeUpdateHook:
		beaconBeforeUpdateHooks = append(beaconBeforeUpdateHooks, beaconHook)
	case boil.BeforeDeleteHook:
		beaconBeforeDeleteHooks = append(beaconBeforeDeleteHooks, beaconHook)
	case boil.BeforeUpsertHook:
		beaconBeforeUpsertHooks = append(beaconBeforeUpsertHooks, beaconHook)
	case boil.AfterInsertHook:
		beaconAfterInsertHooks = append(beaconAfterInsertHooks, beaconHook)
	case boil.AfterSelectHook:
		beaconAfterSelectHooks = append(beaconAfterSelectHooks, beaconHook)
	case boil.AfterUpdateHook:
		beaconAfterUpdateHooks = append(beaconAfterUpdateHooks, beaconHook)
	case boil.AfterDeleteHook:
		beaconAfterDeleteHooks = append(beaconAfterDeleteHooks, beaconHook)
	case boil.AfterUpsertHook:
		beaconAfterUpsertHooks = append(beaconAfterUpsertHooks, beaconHook)
	}
}

// One returns a single beacon record from the query.
func (q beaconQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Beacon, error) {
	o := &Beacon{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "record: failed to execute a one query for beacons")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Beacon records from the query.
func (q beaconQuery) All(ctx context.Context, exec boil.ContextExecutor) (BeaconSlice, error) {
	var o []*Beacon

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "record: failed to assign all query results to Beacon slice")
	}

	if len(beaconAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Beacon records in the query.
func (q beaconQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "record: failed to count beacons rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q beaconQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "record: failed to check if beacons exists")
	}

	return count > 0, nil
}

// ClassRoom pointed to by the foreign key.
func (o *Beacon) ClassRoom(mods ...qm.QueryMod) classRoomQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.ClassRoomID),
	}

	queryMods = append(queryMods, mods...)

	query := ClassRooms(queryMods...)
	queries.SetFrom(query.Query, "\"class_rooms\"")

	return query
}

// LoadClassRoom allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (beaconL) LoadClassRoom(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBeacon interface{}, mods queries.Applicator) error {
	var slice []*Beacon
	var object *Beacon

	if singular {
		object = maybeBeacon.(*Beacon)
	} else {
		slice = *maybeBeacon.(*[]*Beacon)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &beaconR{}
		}
		args = append(args, object.ClassRoomID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &beaconR{}
			}

			for _, a := range args {
				if a == obj.ClassRoomID {
					continue Outer
				}
			}

			args = append(args, obj.ClassRoomID)

		}
	}

	query := NewQuery(qm.From(`class_rooms`), qm.WhereIn(`id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ClassRoom")
	}

	var resultSlice []*ClassRoom
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ClassRoom")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for class_rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for class_rooms")
	}

	if len(beaconAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ClassRoom = foreign
		if foreign.R == nil {
			foreign.R = &classRoomR{}
		}
		foreign.R.Beacons = append(foreign.R.Beacons, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClassRoomID == foreign.ID {
				local.R.ClassRoom = foreign
				if foreign.R == nil {
					foreign.R = &classRoomR{}
				}
				foreign.R.Beacons = append(foreign.R.Beacons, local)
				break
			}
		}
	}

	return nil
}

// SetClassRoom of the beacon to the related item.
// Sets o.R.ClassRoom to related.
// Adds o to related.R.Beacons.
func (o *Beacon) SetClassRoom(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ClassRoom) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"beacons\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"class_room_id"}),
		strmangle.WhereClause("\"", "\"", 2, beaconPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClassRoomID = related.ID
	if o.R == nil {
		o.R = &beaconR{
			ClassRoom: related,
		}
	} else {
		o.R.ClassRoom = related
	}

	if related.R == nil {
		related.R = &classRoomR{
			Beacons: BeaconSlice{o},
		}
	} else {
		related.R.Beacons = append(related.R.Beacons, o)
	}

	return nil
}

// Beacons retrieves all the records using an executor.
func Beacons(mods ...qm.QueryMod) beaconQuery {
	mods = append(mods, qm.From("\"beacons\""))
	return beaconQuery{NewQuery(mods...)}
}

// FindBeacon retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBeacon(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Beacon, error) {
	beaconObj := &Beacon{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"beacons\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, beaconObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "record: unable to select from beacons")
	}

	return beaconObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Beacon) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("record: no beacons provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(beaconColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	beaconInsertCacheMut.RLock()
	cache, cached := beaconInsertCache[key]
	beaconInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			beaconColumns,
			beaconColumnsWithDefault,
			beaconColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(beaconType, beaconMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(beaconType, beaconMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"beacons\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"beacons\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "record: unable to insert into beacons")
	}

	if !cached {
		beaconInsertCacheMut.Lock()
		beaconInsertCache[key] = cache
		beaconInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Beacon.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Beacon) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	beaconUpdateCacheMut.RLock()
	cache, cached := beaconUpdateCache[key]
	beaconUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			beaconColumns,
			beaconPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("record: unable to update beacons, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"beacons\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, beaconPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(beaconType, beaconMapping, append(wl, beaconPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to update beacons row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: failed to get rows affected by update for beacons")
	}

	if !cached {
		beaconUpdateCacheMut.Lock()
		beaconUpdateCache[key] = cache
		beaconUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q beaconQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to update all for beacons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to retrieve rows affected for beacons")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BeaconSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("record: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), beaconPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"beacons\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, beaconPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to update all in beacon slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to retrieve rows affected all in update all beacon")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Beacon) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("record: no beacons provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(beaconColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	beaconUpsertCacheMut.RLock()
	cache, cached := beaconUpsertCache[key]
	beaconUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			beaconColumns,
			beaconColumnsWithDefault,
			beaconColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			beaconColumns,
			beaconPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("record: unable to upsert beacons, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(beaconPrimaryKeyColumns))
			copy(conflict, beaconPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"beacons\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(beaconType, beaconMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(beaconType, beaconMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "record: unable to upsert beacons")
	}

	if !cached {
		beaconUpsertCacheMut.Lock()
		beaconUpsertCache[key] = cache
		beaconUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Beacon record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Beacon) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("record: no Beacon provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), beaconPrimaryKeyMapping)
	sql := "DELETE FROM \"beacons\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to delete from beacons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: failed to get rows affected by delete for beacons")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q beaconQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("record: no beaconQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to delete all from beacons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: failed to get rows affected by deleteall for beacons")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BeaconSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("record: no Beacon slice provided for delete all")
	}

	if len(o) == 0 {
		return 0, nil
	}

	if len(beaconBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), beaconPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"beacons\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, beaconPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "record: unable to delete all from beacon slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "record: failed to get rows affected by deleteall for beacons")
	}

	if len(beaconAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Beacon) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBeacon(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BeaconSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BeaconSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), beaconPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"beacons\".* FROM \"beacons\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, beaconPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "record: unable to reload all in BeaconSlice")
	}

	*o = slice

	return nil
}

// BeaconExists checks if the Beacon row exists.
func BeaconExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"beacons\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}

	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "record: unable to check if beacons exists")
	}

	return exists, nil
}
