// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	ClassRooms string
	Sessions   string
	Tags       string
	UserTags   string
	Users      string
}{
	ClassRooms: "class_rooms",
	Sessions:   "sessions",
	Tags:       "tags",
	UserTags:   "user_tags",
	Users:      "users",
}
