// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

var TableNames = struct {
	Beacons       string
	ClassRooms    string
	Sessions      string
	Tags          string
	UserPositions string
	UserTags      string
	Users         string
}{
	Beacons:       "beacons",
	ClassRooms:    "class_rooms",
	Sessions:      "sessions",
	Tags:          "tags",
	UserPositions: "user_positions",
	UserTags:      "user_tags",
	Users:         "users",
}
