// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package record

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Beacons", testBeaconsUpsert)

	t.Run("ClassRoomTags", testClassRoomTagsUpsert)

	t.Run("ClassRooms", testClassRoomsUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("Tags", testTagsUpsert)

	t.Run("UserPositions", testUserPositionsUpsert)

	t.Run("UserTags", testUserTagsUpsert)

	t.Run("Users", testUsersUpsert)
}
