// Code generated by protoc-gen-go. DO NOT EDIT.
// source: building.proto

package type_pb // import "github.com/gedorinku/tsugidoko-server/api/type"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Building struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude             float64  `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Building) Reset()         { *m = Building{} }
func (m *Building) String() string { return proto.CompactTextString(m) }
func (*Building) ProtoMessage()    {}
func (*Building) Descriptor() ([]byte, []int) {
	return fileDescriptor_building_343eeed02016afbb, []int{0}
}
func (m *Building) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Building.Unmarshal(m, b)
}
func (m *Building) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Building.Marshal(b, m, deterministic)
}
func (dst *Building) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Building.Merge(dst, src)
}
func (m *Building) XXX_Size() int {
	return xxx_messageInfo_Building.Size(m)
}
func (m *Building) XXX_DiscardUnknown() {
	xxx_messageInfo_Building.DiscardUnknown(m)
}

var xxx_messageInfo_Building proto.InternalMessageInfo

func (m *Building) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Building) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Building) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Building) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*Building)(nil), "gedorinku.tsugidoko_server.type.Building")
}

func init() { proto.RegisterFile("building.proto", fileDescriptor_building_343eeed02016afbb) }

var fileDescriptor_building_343eeed02016afbb = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcf, 0xb1, 0xca, 0x83, 0x30,
	0x10, 0x07, 0x70, 0xe2, 0xe7, 0x57, 0x34, 0x83, 0x43, 0x26, 0x29, 0x85, 0x4a, 0x27, 0x97, 0x26,
	0x43, 0xa1, 0x14, 0xba, 0xf9, 0x08, 0x8e, 0x5d, 0xc4, 0x34, 0x21, 0x1e, 0x6a, 0x12, 0x62, 0x52,
	0xe8, 0xdb, 0x17, 0xb5, 0xd8, 0xe5, 0xb8, 0xbb, 0x3f, 0x07, 0xbf, 0xc3, 0x19, 0x0f, 0x30, 0x08,
	0xd0, 0x8a, 0x5a, 0x67, 0xbc, 0x21, 0x47, 0x25, 0x85, 0x71, 0xa0, 0xfb, 0x40, 0xfd, 0x14, 0x14,
	0x08, 0xd3, 0x9b, 0x66, 0x92, 0xee, 0x25, 0x1d, 0xf5, 0x6f, 0x2b, 0x4f, 0x1d, 0x4e, 0xaa, 0xef,
	0x09, 0xc9, 0x70, 0x04, 0x22, 0x47, 0x05, 0x2a, 0xff, 0xeb, 0x08, 0x04, 0x21, 0x38, 0xd6, 0xed,
	0x28, 0xf3, 0xa8, 0x40, 0x65, 0x5a, 0x2f, 0x3d, 0xd9, 0xe3, 0x64, 0x68, 0x3d, 0xf8, 0x20, 0x64,
	0xfe, 0x57, 0xa0, 0x12, 0xd5, 0xdb, 0x4c, 0x0e, 0x38, 0x1d, 0x8c, 0x56, 0x6b, 0x18, 0x2f, 0xe1,
	0x6f, 0x51, 0xdd, 0x1e, 0x57, 0x05, 0xbe, 0x0b, 0x9c, 0x3e, 0xcd, 0xc8, 0x36, 0x17, 0xdb, 0x5c,
	0xe7, 0xd5, 0xc5, 0x5a, 0x0b, 0x6c, 0xb6, 0xdd, 0xe7, 0xd2, 0x58, 0xce, 0x77, 0xcb, 0x2f, 0x97,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x8d, 0x3c, 0xe8, 0xdd, 0x00, 0x00, 0x00,
}
