// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sessions.proto

package api_pb // import "github.com/gedorinku/tsugidoko-server/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UesrId               uint32   `protobuf:"varint,2,opt,name=uesr_id,json=uesrId,proto3" json:"uesr_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_sessions_991196f100467d71, []int{0}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (dst *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(dst, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Session) GetUesrId() uint32 {
	if m != nil {
		return m.UesrId
	}
	return 0
}

type CreateSessionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sessions_991196f100467d71, []int{1}
}
func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(dst, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateSessionRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type DeleteSessionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_sessions_991196f100467d71, []int{2}
}
func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(dst, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Session)(nil), "gedorinku.tsugidoko_server.Session")
	proto.RegisterType((*CreateSessionRequest)(nil), "gedorinku.tsugidoko_server.CreateSessionRequest")
	proto.RegisterType((*DeleteSessionRequest)(nil), "gedorinku.tsugidoko_server.DeleteSessionRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/gedorinku.tsugidoko_server.SessionService/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gedorinku.tsugidoko_server.SessionService/DeleteSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
type SessionServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*empty.Empty, error)
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gedorinku.tsugidoko_server.SessionService/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gedorinku.tsugidoko_server.SessionService/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gedorinku.tsugidoko_server.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionService_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _SessionService_DeleteSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sessions.proto",
}

func init() { proto.RegisterFile("sessions.proto", fileDescriptor_sessions_991196f100467d71) }

var fileDescriptor_sessions_991196f100467d71 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xcd, 0x4a, 0xfb, 0x40,
	0x14, 0xc5, 0x49, 0xf9, 0xd3, 0xfe, 0x73, 0xa5, 0x05, 0x87, 0x52, 0x25, 0x2a, 0x94, 0xb8, 0x29,
	0x05, 0x27, 0xa5, 0xee, 0x74, 0xe5, 0x27, 0x74, 0x9b, 0xee, 0xdc, 0x94, 0x49, 0x73, 0x8d, 0x43,
	0xdb, 0x4c, 0x9c, 0x8f, 0x8a, 0xe0, 0xca, 0x57, 0xf0, 0xd1, 0x7c, 0x05, 0x1f, 0xc3, 0x85, 0x24,
	0x99, 0xa6, 0x54, 0x6a, 0x77, 0x73, 0xef, 0x99, 0x7b, 0x7e, 0x77, 0xe6, 0x40, 0x4b, 0xa1, 0x52,
	0x5c, 0xa4, 0x8a, 0x66, 0x52, 0x68, 0x41, 0xbc, 0x04, 0x63, 0x21, 0x79, 0x3a, 0x33, 0x54, 0x2b,
	0x93, 0xf0, 0x58, 0xcc, 0xc4, 0x44, 0xa1, 0x5c, 0xa2, 0xf4, 0x8e, 0x13, 0x21, 0x92, 0x39, 0x06,
	0x2c, 0xe3, 0x01, 0x4b, 0x53, 0xa1, 0x99, 0x5e, 0x4f, 0x7a, 0x47, 0x56, 0x2d, 0xaa, 0xc8, 0x3c,
	0x06, 0xb8, 0xc8, 0xf4, 0x6b, 0x29, 0xfa, 0x57, 0xd0, 0x18, 0x97, 0x20, 0x72, 0x02, 0x60, 0x99,
	0x13, 0x1e, 0x1f, 0x3a, 0x5d, 0xa7, 0xe7, 0x86, 0xae, 0xed, 0x8c, 0x62, 0x72, 0x00, 0x0d, 0x83,
	0x4a, 0xe6, 0x5a, 0xad, 0xeb, 0xf4, 0x9a, 0x61, 0x3d, 0x2f, 0x47, 0xb1, 0x7f, 0x0f, 0xed, 0x1b,
	0x89, 0x4c, 0xa3, 0x35, 0x0a, 0xf1, 0xd9, 0xa0, 0xd2, 0x84, 0xc0, 0xbf, 0x94, 0x2d, 0xd0, 0x3a,
	0x15, 0x67, 0xe2, 0xc1, 0xff, 0x8c, 0x29, 0xf5, 0x22, 0x64, 0xe9, 0xe2, 0x86, 0x55, 0xed, 0x77,
	0xa0, 0x7d, 0x8b, 0x73, 0xfc, 0xed, 0x33, 0xfc, 0x76, 0xa0, 0x65, 0x5b, 0x63, 0x94, 0x4b, 0x3e,
	0x45, 0xf2, 0x06, 0xcd, 0x0d, 0x24, 0x19, 0xd0, 0xbf, 0xbf, 0x87, 0x6e, 0xdb, 0xce, 0x3b, 0xdd,
	0x35, 0x61, 0xef, 0xfa, 0xed, 0xf7, 0xcf, 0xaf, 0x8f, 0x5a, 0xcb, 0x77, 0x83, 0x55, 0x1a, 0x17,
	0x4e, 0x9f, 0xcc, 0xa1, 0xb9, 0xb1, 0xe8, 0x6e, 0xfa, 0xb6, 0x37, 0x79, 0x1d, 0x5a, 0x86, 0x42,
	0x57, 0xa1, 0xd0, 0xbb, 0x3c, 0x14, 0x7f, 0xbf, 0x00, 0xee, 0xf5, 0xd7, 0xc0, 0xeb, 0xe1, 0xc3,
	0x20, 0xe1, 0xfa, 0xc9, 0x44, 0x74, 0x2a, 0x16, 0x41, 0x05, 0x0a, 0x2a, 0xd0, 0x59, 0x09, 0xca,
	0xd3, 0xbf, 0x64, 0x19, 0x9f, 0x64, 0x51, 0x54, 0x2f, 0x6c, 0xcf, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0xfd, 0x18, 0x36, 0x45, 0x02, 0x00, 0x00,
}
