// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tags.proto

package api_pb // import "github.com/gedorinku/tsugidoko-server/api"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tag struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{0}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (dst *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(dst, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TagCount struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagCount) Reset()         { *m = TagCount{} }
func (m *TagCount) String() string { return proto.CompactTextString(m) }
func (*TagCount) ProtoMessage()    {}
func (*TagCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{1}
}
func (m *TagCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagCount.Unmarshal(m, b)
}
func (m *TagCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagCount.Marshal(b, m, deterministic)
}
func (dst *TagCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagCount.Merge(dst, src)
}
func (m *TagCount) XXX_Size() int {
	return xxx_messageInfo_TagCount.Size(m)
}
func (m *TagCount) XXX_DiscardUnknown() {
	xxx_messageInfo_TagCount.DiscardUnknown(m)
}

var xxx_messageInfo_TagCount proto.InternalMessageInfo

func (m *TagCount) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *TagCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListTagsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagsRequest) Reset()         { *m = ListTagsRequest{} }
func (m *ListTagsRequest) String() string { return proto.CompactTextString(m) }
func (*ListTagsRequest) ProtoMessage()    {}
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{2}
}
func (m *ListTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagsRequest.Unmarshal(m, b)
}
func (m *ListTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagsRequest.Marshal(b, m, deterministic)
}
func (dst *ListTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagsRequest.Merge(dst, src)
}
func (m *ListTagsRequest) XXX_Size() int {
	return xxx_messageInfo_ListTagsRequest.Size(m)
}
func (m *ListTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagsRequest proto.InternalMessageInfo

type ListTagsResponse struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTagsResponse) Reset()         { *m = ListTagsResponse{} }
func (m *ListTagsResponse) String() string { return proto.CompactTextString(m) }
func (*ListTagsResponse) ProtoMessage()    {}
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{3}
}
func (m *ListTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTagsResponse.Unmarshal(m, b)
}
func (m *ListTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTagsResponse.Marshal(b, m, deterministic)
}
func (dst *ListTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTagsResponse.Merge(dst, src)
}
func (m *ListTagsResponse) XXX_Size() int {
	return xxx_messageInfo_ListTagsResponse.Size(m)
}
func (m *ListTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTagsResponse proto.InternalMessageInfo

func (m *ListTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetTagRequest struct {
	TagId                int32    `protobuf:"varint,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagRequest) Reset()         { *m = GetTagRequest{} }
func (m *GetTagRequest) String() string { return proto.CompactTextString(m) }
func (*GetTagRequest) ProtoMessage()    {}
func (*GetTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{4}
}
func (m *GetTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagRequest.Unmarshal(m, b)
}
func (m *GetTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagRequest.Marshal(b, m, deterministic)
}
func (dst *GetTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagRequest.Merge(dst, src)
}
func (m *GetTagRequest) XXX_Size() int {
	return xxx_messageInfo_GetTagRequest.Size(m)
}
func (m *GetTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagRequest proto.InternalMessageInfo

func (m *GetTagRequest) GetTagId() int32 {
	if m != nil {
		return m.TagId
	}
	return 0
}

type CreateTagRequest struct {
	Tag                  *Tag     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTagRequest) Reset()         { *m = CreateTagRequest{} }
func (m *CreateTagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTagRequest) ProtoMessage()    {}
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tags_34f3b765826737c1, []int{5}
}
func (m *CreateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagRequest.Unmarshal(m, b)
}
func (m *CreateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagRequest.Marshal(b, m, deterministic)
}
func (dst *CreateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagRequest.Merge(dst, src)
}
func (m *CreateTagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTagRequest.Size(m)
}
func (m *CreateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagRequest proto.InternalMessageInfo

func (m *CreateTagRequest) GetTag() *Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
	proto.RegisterType((*Tag)(nil), "gedorinku.tsugidoko_server.Tag")
	proto.RegisterType((*TagCount)(nil), "gedorinku.tsugidoko_server.TagCount")
	proto.RegisterType((*ListTagsRequest)(nil), "gedorinku.tsugidoko_server.ListTagsRequest")
	proto.RegisterType((*ListTagsResponse)(nil), "gedorinku.tsugidoko_server.ListTagsResponse")
	proto.RegisterType((*GetTagRequest)(nil), "gedorinku.tsugidoko_server.GetTagRequest")
	proto.RegisterType((*CreateTagRequest)(nil), "gedorinku.tsugidoko_server.CreateTagRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TagServiceClient is the client API for TagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagServiceClient interface {
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error)
}

type tagServiceClient struct {
	cc *grpc.ClientConn
}

func NewTagServiceClient(cc *grpc.ClientConn) TagServiceClient {
	return &tagServiceClient{cc}
}

func (c *tagServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, "/gedorinku.tsugidoko_server.TagService/ListTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/gedorinku.tsugidoko_server.TagService/GetTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error) {
	out := new(Tag)
	err := c.cc.Invoke(ctx, "/gedorinku.tsugidoko_server.TagService/CreateTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServiceServer is the server API for TagService service.
type TagServiceServer interface {
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	GetTag(context.Context, *GetTagRequest) (*Tag, error)
	CreateTag(context.Context, *CreateTagRequest) (*Tag, error)
}

func RegisterTagServiceServer(s *grpc.Server, srv TagServiceServer) {
	s.RegisterService(&_TagService_serviceDesc, srv)
}

func _TagService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gedorinku.tsugidoko_server.TagService/ListTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gedorinku.tsugidoko_server.TagService/GetTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).GetTag(ctx, req.(*GetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gedorinku.tsugidoko_server.TagService/CreateTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TagService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gedorinku.tsugidoko_server.TagService",
	HandlerType: (*TagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTags",
			Handler:    _TagService_ListTags_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _TagService_GetTag_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _TagService_CreateTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tags.proto",
}

func init() { proto.RegisterFile("tags.proto", fileDescriptor_tags_34f3b765826737c1) }

var fileDescriptor_tags_34f3b765826737c1 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0x86, 0xd3, 0x42, 0x11, 0x8e, 0x82, 0x78, 0xa2, 0x86, 0x54, 0x13, 0xc9, 0x2c, 0x0c, 0x44,
	0x6d, 0x15, 0x76, 0xba, 0x93, 0x18, 0x62, 0xe2, 0xaa, 0x74, 0xe5, 0x86, 0x4c, 0xe9, 0x38, 0x4e,
	0x80, 0x99, 0xda, 0x99, 0x92, 0x18, 0xe3, 0xc6, 0x57, 0xf0, 0xd1, 0x7c, 0x01, 0x17, 0x3e, 0x88,
	0xe9, 0x94, 0xdb, 0x7b, 0x2f, 0xc9, 0x05, 0xee, 0xae, 0xd3, 0xf9, 0xcf, 0xff, 0x9f, 0xef, 0x4f,
	0x0b, 0x60, 0x28, 0xd7, 0x41, 0x96, 0x2b, 0xa3, 0xd0, 0xe7, 0x2c, 0x55, 0xb9, 0x90, 0xeb, 0x22,
	0x30, 0xba, 0xe0, 0x22, 0x55, 0x6b, 0xb5, 0xd4, 0x2c, 0xdf, 0xb1, 0xdc, 0x7f, 0xca, 0x95, 0xe2,
	0x1b, 0x16, 0xd2, 0x4c, 0x84, 0x54, 0x4a, 0x65, 0xa8, 0x11, 0x4a, 0xee, 0x27, 0xfd, 0x27, 0xfb,
	0x5b, 0x7b, 0x4a, 0x8a, 0x2f, 0x21, 0xdb, 0x66, 0xe6, 0x7b, 0x75, 0x49, 0xc6, 0xd0, 0x88, 0x29,
	0xc7, 0x1e, 0xb8, 0x22, 0x1d, 0x38, 0x43, 0x67, 0xe4, 0x45, 0xae, 0x48, 0x11, 0xa1, 0x29, 0xe9,
	0x96, 0x0d, 0xdc, 0xa1, 0x33, 0xea, 0x44, 0xf6, 0x99, 0x2c, 0xa0, 0x1d, 0x53, 0x3e, 0x53, 0x85,
	0x34, 0xf8, 0x06, 0x1a, 0x86, 0x72, 0x3b, 0x70, 0x77, 0xf2, 0x2c, 0xb8, 0x79, 0xb7, 0x20, 0xa6,
	0x3c, 0x2a, 0xb5, 0xf8, 0x10, 0xbc, 0x55, 0x39, 0x6b, 0x3d, 0xbd, 0xa8, 0x3a, 0x90, 0x07, 0x70,
	0xff, 0x93, 0xd0, 0x26, 0xa6, 0x5c, 0x47, 0xec, 0x5b, 0xc1, 0xb4, 0x21, 0x73, 0xe8, 0x5f, 0xbe,
	0xd2, 0x99, 0x92, 0x9a, 0xe1, 0x14, 0x9a, 0x65, 0x17, 0x03, 0x67, 0xd8, 0x38, 0x27, 0xd0, 0x8a,
	0xc9, 0x73, 0xe8, 0xce, 0x59, 0xe9, 0xb3, 0x77, 0xc6, 0x47, 0xd0, 0x32, 0x94, 0x2f, 0x6b, 0x52,
	0xcf, 0x50, 0xfe, 0x31, 0x25, 0x1f, 0xa0, 0x3f, 0xcb, 0x19, 0x35, 0xec, 0x8a, 0xf4, 0xf6, 0x80,
	0x93, 0xbf, 0x2e, 0x40, 0x4c, 0xf9, 0x82, 0xe5, 0x3b, 0xb1, 0x62, 0x68, 0xa0, 0x7d, 0x81, 0x81,
	0x2f, 0x8e, 0x19, 0x1c, 0xf0, 0xfb, 0x2f, 0xcf, 0x13, 0x57, 0xcd, 0x90, 0xee, 0xaf, 0x3f, 0xff,
	0x7e, 0xbb, 0x77, 0xd0, 0x0b, 0x4b, 0x66, 0xdc, 0x40, 0xab, 0x62, 0xc6, 0xf1, 0x31, 0x9b, 0x6b,
	0xbd, 0xf8, 0xa7, 0xf8, 0xc8, 0x63, 0x1b, 0xd2, 0xc7, 0x9e, 0x0d, 0x09, 0x7f, 0x54, 0x2d, 0xfe,
	0x44, 0x09, 0x9d, 0xba, 0x39, 0x3c, 0xba, 0xf7, 0x61, 0xc1, 0xa7, 0x33, 0xd1, 0x66, 0xde, 0x23,
	0x15, 0xd8, 0xdb, 0xb2, 0xe2, 0xf7, 0x93, 0xcf, 0xaf, 0xb9, 0x30, 0x5f, 0x8b, 0x24, 0x58, 0xa9,
	0x6d, 0x58, 0x1b, 0x84, 0xb5, 0xc1, 0xab, 0xca, 0xa0, 0xfc, 0x13, 0xde, 0xd1, 0x4c, 0x2c, 0xb3,
	0x24, 0x69, 0xd9, 0x0f, 0x7d, 0xfa, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x39, 0xc1, 0x2c, 0x2b, 0x4d,
	0x03, 0x00, 0x00,
}
